# Generated by Django 2.2.20 on 2021-06-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customtext_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='title',
        ),
        migrations.AddField(
            model_name='customtext',
            name='chart',
            field=models.URLField(blank=True, null=True),
        ),
    ]
